apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwdeployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: hwpod
  template:
    metadata:
      labels:
        app: hwpod
    spec:
      containers:
      - name: helloworld
        image: hello-world